# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: filesystem.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x66ilesystem.proto\"$\n\x08\x46ilename\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t\"@\n\x0e\x43onversionData\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nconversion\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\"#\n\nResponse_2\x12\x15\n\ramount_result\x18\x01 \x01(\x01\x32R\n\nFileSystem\x12 \n\x06Upload\x12\t.Filename\x1a\t.Response\"\x00\x12\"\n\x08\x44ownload\x12\t.Filename\x1a\t.Response\"\x00\x32>\n\x11\x43urrencyConverter\x12)\n\x07\x43onvert\x12\x0f.ConversionData\x1a\x0b.Response_2\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'filesystem_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FILENAME']._serialized_start=20
  _globals['_FILENAME']._serialized_end=56
  _globals['_RESPONSE']._serialized_start=58
  _globals['_RESPONSE']._serialized_end=85
  _globals['_CONVERSIONDATA']._serialized_start=87
  _globals['_CONVERSIONDATA']._serialized_end=151
  _globals['_RESPONSE_2']._serialized_start=153
  _globals['_RESPONSE_2']._serialized_end=188
  _globals['_FILESYSTEM']._serialized_start=190
  _globals['_FILESYSTEM']._serialized_end=272
  _globals['_CURRENCYCONVERTER']._serialized_start=274
  _globals['_CURRENCYCONVERTER']._serialized_end=336
# @@protoc_insertion_point(module_scope)
