version: "3.8"
services:
  central_server:
    build:
      context: ./central_server
    command: air
    env_file:
      - central_server/.env
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ./central_server:/app
    networks:
      - reto-1

networks:
  reto-1: